package com.gckavach.gckavachapp.alert.event;

import com.gckavach.gckavachapp.config.KafkaTopicConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

/**
 * Consumes alert events from Kafka.
 *
 * This component receives lifecycle events generated by the
 * Alert Management module.
 */
@Component
public class AlertEventConsumer {

    private static final Logger log =
            LoggerFactory.getLogger(AlertEventConsumer.class);

    /**
     * Consumes alert events.
     *
     * The containerFactory name must match the bean defined in
     * KafkaConfig.
     *
     * @param event alert event received from Kafka
     */
    @KafkaListener(
            topics = KafkaTopicConfig.ALERT_EVENTS_TOPIC,
            groupId = "gckavacha-alert-consumer",
            containerFactory = "alertEventKafkaListenerContainerFactory"
    )
    public void consume(AlertEvent event) {

        log.info(
                "Received alert event: eventId={}, type={}, alertId={}, status={}",
                event.eventId(),
                event.eventType(),
                event.alterId(),
                event.status()
        );

        switch (event.eventType()) {

            case ALERT_CREATED ->
                    handleAlertCreated(event);

            case ALERT_ACKNOWLEDGED ->
                    handleAlertAcknowledged(event);

            case ALERT_RESOLVED ->
                    handleAlertResolved(event);

            case ALERT_SUPPRESSED ->
                    handleAlertSuppressed(event);
        }
    }

    /**
     * Handles ALERT_CREATED events.
     *
     * @param event alert event
     */
    private void handleAlertCreated(
            AlertEvent event) {

        log.info(
                "Handling ALERT_CREATED: alertId={}",
                event.alterId()
        );
    }

    /**
     * Handles ALERT_ACKNOWLEDGED events.
     *
     * @param event alert event
     */
    private void handleAlertAcknowledged(
            AlertEvent event) {

        log.info(
                "Handling ALERT_ACKNOWLEDGED: alertId={}",
                event.alterId()
        );
    }

    /**
     * Handles ALERT_RESOLVED events.
     *
     * @param event alert event
     */
    private void handleAlertResolved(
            AlertEvent event) {

        log.info(
                "Handling ALERT_RESOLVED: alertId={}",
                event.alterId()
        );
    }

    /**
     * Handles ALERT_SUPPRESSED events.
     *
     * @param event alert event
     */
    private void handleAlertSuppressed(
            AlertEvent event) {

        log.info(
                "Handling ALERT_SUPPRESSED: alertId={}",
                event.alterId()
        );
    }
}